#!/usr/bin/env bash

VERSION="0.0.2"
RR_PREFIX="/usr/local/lib/rr"

version()
{
        echo $VERSION
}

current()
{
        basename "$(readlink "$RR_PREFIX/current")"
}

list()
{
        local active=basename "$(readlink "$RR_PREFIX/current")"
	echo active

        for dir in $RR_PREFIX/rubies/*; do
                local name=$(basename $dir)
                if [[ "$name" == "$active" ]]; then
                        printf "  *  $name\n"
                else
                        printf "     $name\n"
                fi
        done
}

install()
{
	local url="$1"
	local name="$2"
	local rubydir="$RR_PREFIX/rubies/$name"
	local builddir="$rubydir/src"

	mkdir -p $builddir

	pushd "$builddir" > /dev/null
	echo "Downloading $url"
	curl -# $url | tar xz --strip-components=1
	./configure --prefix="$rubydir"
	PREFIX="$rubydir" make && make install
	popd > /dev/null
}

uninstall()
{
	local name="$1"
	local rubydir="$RR_PREFIX/rubies/$name"

	rm -rf "$rubydir"
}

use()
{
	local name="$1"
	local rubydir="$RR_PREFIX/rubies/$name"
	local current = "$RR_PREVIX/current"

        if [[ ! -d "$rubydir" ]]; then
                printf "no such ruby: $name\n" >&2 && exit 1
        fi

        rm -f "$current"
        ln -s "$rubydir" "$current"
        list
}

rr()
{
        if [[ $# == 0 ]]; then
                list
        else
                case "$1" in
                        -v|--version)
                                version ;;
			install)
				shift install "$@" ;;
			uninstall)
				shift uninstall "$@" ;;
                        *)
                                use "$@" ;;
                esac
        fi
}

rr "$@"